INSERT INTO stories (title, content, status)
VALUES ('CSS The Definitive Guide', 'Sed in mauris eget sem egestas aliquam. Vestibulum sapien libero, hendrerit non arcu eget, ultricies tincidunt purus. Fusce tempus molestie nisi eget ullamcorper. Nunc sagittis sapien eget ex venenatis, eu interdum nibh ullamcorper. Curabitur vestibulum tortor a purus blandit tempus. Vivamus commodo volutpat iaculis. Donec ultricies purus lacus, vitae sollicitudin odio semper nec. Aenean rutrum nisi ac urna aliquet scelerisque. Suspendisse imperdiet ligula nisl, in molestie eros suscipit vitae. Donec eget quam posuere, finibus velit in, placerat nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec condimentum pellentesque tempus. Cras vitae quam nec diam semper volutpat in eu justo. Etiam eu gravida lectus, ut interdum augue. Maecenas mauris lacus, lacinia ac dignissim eget, hendrerit ut dui. Quisque eleifend lacus et porttitor cursus.
Aenean et mi molestie, iaculis lectus id, condimentum ex. In pretium fermentum sem, et ultrices orci tristique a. Sed ut faucibus augue. Phasellus dignissim tristique ante id accumsan. Donec convallis eget nunc quis fringilla. Sed feugiat neque sit amet tortor vestibulum, et elementum libero pharetra. Praesent euismod lorem ullamcorper ipsum egestas posuere. Aliquam in porttitor dolor. Praesent id libero sed felis accumsan eleifend. Vivamus sit amet magna elementum, rhoncus erat eleifend, interdum eros. Fusce lacus dolor, ornare ut hendrerit at, blandit at elit. Nullam euismod velit in diam consequat facilisis. Vestibulum feugiat feugiat est, sed vehicula quam tempus at. Phasellus laoreet nulla lacus, in lacinia orci accumsan id. Aenean volutpat porta nunc non dictum. Nulla rhoncus, ex eget vulputate porta, leo mauris consectetur magna, id lacinia sapien magna eu dolor.
Nulla nec facilisis urna. Pellentesque eget nulla auctor, blandit leo eget, tincidunt mauris. Phasellus id consectetur sem, sit amet rutrum leo. Suspendisse lacinia, orci placerat luctus sollicitudin, libero diam fringilla justo, fringilla dignissim eros nisi nec velit. Sed auctor sagittis libero, at pulvinar nibh sagittis ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed in velit sed erat lacinia laoreet. Phasellus ut nunc at massa sodales tempor ut eget dui. Fusce suscipit ultrices lobortis. Mauris blandit, justo eget sagittis varius, nibh erat ultrices quam, et finibus sapien turpis ac ex. Quisque pulvinar ipsum eget magna pulvinar fringilla. Fusce rhoncus suscipit urna sit amet hendrerit. Phasellus at vulputate lorem.
', 'read');

INSERT INTO stories (title, content, status)
VALUES ('To Kill A Mockingbird', 'Sed in mauris eget sem egestas aliquam. Vestibulum sapien libero, hendrerit non arcu eget, ultricies tincidunt purus. Fusce tempus molestie nisi eget ullamcorper. Nunc sagittis sapien eget ex venenatis, eu interdum nibh ullamcorper. Curabitur vestibulum tortor a purus blandit tempus. Vivamus commodo volutpat iaculis. Donec ultricies purus lacus, vitae sollicitudin odio semper nec. Aenean rutrum nisi ac urna aliquet scelerisque. Suspendisse imperdiet ligula nisl, in molestie eros suscipit vitae. Donec eget quam posuere, finibus velit in, placerat nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec condimentum pellentesque tempus. Cras vitae quam nec diam semper volutpat in eu justo. Etiam eu gravida lectus, ut interdum augue. Maecenas mauris lacus, lacinia ac dignissim eget, hendrerit ut dui. Quisque eleifend lacus et porttitor cursus.
Aenean et mi molestie, iaculis lectus id, condimentum ex. In pretium fermentum sem, et ultrices orci tristique a. Sed ut faucibus augue. Phasellus dignissim tristique ante id accumsan. Donec convallis eget nunc quis fringilla. Sed feugiat neque sit amet tortor vestibulum, et elementum libero pharetra. Praesent euismod lorem ullamcorper ipsum egestas posuere. Aliquam in porttitor dolor. Praesent id libero sed felis accumsan eleifend. Vivamus sit amet magna elementum, rhoncus erat eleifend, interdum eros. Fusce lacus dolor, ornare ut hendrerit at, blandit at elit. Nullam euismod velit in diam consequat facilisis. Vestibulum feugiat feugiat est, sed vehicula quam tempus at. Phasellus laoreet nulla lacus, in lacinia orci accumsan id. Aenean volutpat porta nunc non dictum. Nulla rhoncus, ex eget vulputate porta, leo mauris consectetur magna, id lacinia sapien magna eu dolor.
Nulla nec facilisis urna. Pellentesque eget nulla auctor, blandit leo eget, tincidunt mauris. Phasellus id consectetur sem, sit amet rutrum leo. Suspendisse lacinia, orci placerat luctus sollicitudin, libero diam fringilla justo, fringilla dignissim eros nisi nec velit. Sed auctor sagittis libero, at pulvinar nibh sagittis ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed in velit sed erat lacinia laoreet. Phasellus ut nunc at massa sodales tempor ut eget dui. Fusce suscipit ultrices lobortis. Mauris blandit, justo eget sagittis varius, nibh erat ultrices quam, et finibus sapien turpis ac ex. Quisque pulvinar ipsum eget magna pulvinar fringilla. Fusce rhoncus suscipit urna sit amet hendrerit. Phasellus at vulputate lorem.
', 'read');

INSERT INTO stories (title, content, status)
VALUES ('Space X', 'Sed in mauris eget sem egestas aliquam. Vestibulum sapien libero, hendrerit non arcu eget, ultricies tincidunt purus. Fusce tempus molestie nisi eget ullamcorper. Nunc sagittis sapien eget ex venenatis, eu interdum nibh ullamcorper. Curabitur vestibulum tortor a purus blandit tempus. Vivamus commodo volutpat iaculis. Donec ultricies purus lacus, vitae sollicitudin odio semper nec. Aenean rutrum nisi ac urna aliquet scelerisque. Suspendisse imperdiet ligula nisl, in molestie eros suscipit vitae. Donec eget quam posuere, finibus velit in, placerat nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec condimentum pellentesque tempus. Cras vitae quam nec diam semper volutpat in eu justo. Etiam eu gravida lectus, ut interdum augue. Maecenas mauris lacus, lacinia ac dignissim eget, hendrerit ut dui. Quisque eleifend lacus et porttitor cursus.
Aenean et mi molestie, iaculis lectus id, condimentum ex. In pretium fermentum sem, et ultrices orci tristique a. Sed ut faucibus augue. Phasellus dignissim tristique ante id accumsan. Donec convallis eget nunc quis fringilla. Sed feugiat neque sit amet tortor vestibulum, et elementum libero pharetra. Praesent euismod lorem ullamcorper ipsum egestas posuere. Aliquam in porttitor dolor. Praesent id libero sed felis accumsan eleifend. Vivamus sit amet magna elementum, rhoncus erat eleifend, interdum eros. Fusce lacus dolor, ornare ut hendrerit at, blandit at elit. Nullam euismod velit in diam consequat facilisis. Vestibulum feugiat feugiat est, sed vehicula quam tempus at. Phasellus laoreet nulla lacus, in lacinia orci accumsan id. Aenean volutpat porta nunc non dictum. Nulla rhoncus, ex eget vulputate porta, leo mauris consectetur magna, id lacinia sapien magna eu dolor.
Nulla nec facilisis urna. Pellentesque eget nulla auctor, blandit leo eget, tincidunt mauris. Phasellus id consectetur sem, sit amet rutrum leo. Suspendisse lacinia, orci placerat luctus sollicitudin, libero diam fringilla justo, fringilla dignissim eros nisi nec velit. Sed auctor sagittis libero, at pulvinar nibh sagittis ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed in velit sed erat lacinia laoreet. Phasellus ut nunc at massa sodales tempor ut eget dui. Fusce suscipit ultrices lobortis. Mauris blandit, justo eget sagittis varius, nibh erat ultrices quam, et finibus sapien turpis ac ex. Quisque pulvinar ipsum eget magna pulvinar fringilla. Fusce rhoncus suscipit urna sit amet hendrerit. Phasellus at vulputate lorem.
', 'read');

INSERT INTO stories (title, content, status)
VALUES ('Harry Potter and the Philosophers Stone', 'Sed in mauris eget sem egestas aliquam. Vestibulum sapien libero, hendrerit non arcu eget, ultricies tincidunt purus. Fusce tempus molestie nisi eget ullamcorper. Nunc sagittis sapien eget ex venenatis, eu interdum nibh ullamcorper. Curabitur vestibulum tortor a purus blandit tempus. Vivamus commodo volutpat iaculis. Donec ultricies purus lacus, vitae sollicitudin odio semper nec. Aenean rutrum nisi ac urna aliquet scelerisque. Suspendisse imperdiet ligula nisl, in molestie eros suscipit vitae. Donec eget quam posuere, finibus velit in, placerat nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec condimentum pellentesque tempus. Cras vitae quam nec diam semper volutpat in eu justo. Etiam eu gravida lectus, ut interdum augue. Maecenas mauris lacus, lacinia ac dignissim eget, hendrerit ut dui. Quisque eleifend lacus et porttitor cursus.
Aenean et mi molestie, iaculis lectus id, condimentum ex. In pretium fermentum sem, et ultrices orci tristique a. Sed ut faucibus augue. Phasellus dignissim tristique ante id accumsan. Donec convallis eget nunc quis fringilla. Sed feugiat neque sit amet tortor vestibulum, et elementum libero pharetra. Praesent euismod lorem ullamcorper ipsum egestas posuere. Aliquam in porttitor dolor. Praesent id libero sed felis accumsan eleifend. Vivamus sit amet magna elementum, rhoncus erat eleifend, interdum eros. Fusce lacus dolor, ornare ut hendrerit at, blandit at elit. Nullam euismod velit in diam consequat facilisis. Vestibulum feugiat feugiat est, sed vehicula quam tempus at. Phasellus laoreet nulla lacus, in lacinia orci accumsan id. Aenean volutpat porta nunc non dictum. Nulla rhoncus, ex eget vulputate porta, leo mauris consectetur magna, id lacinia sapien magna eu dolor.
Nulla nec facilisis urna. Pellentesque eget nulla auctor, blandit leo eget, tincidunt mauris. Phasellus id consectetur sem, sit amet rutrum leo. Suspendisse lacinia, orci placerat luctus sollicitudin, libero diam fringilla justo, fringilla dignissim eros nisi nec velit. Sed auctor sagittis libero, at pulvinar nibh sagittis ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed in velit sed erat lacinia laoreet. Phasellus ut nunc at massa sodales tempor ut eget dui. Fusce suscipit ultrices lobortis. Mauris blandit, justo eget sagittis varius, nibh erat ultrices quam, et finibus sapien turpis ac ex. Quisque pulvinar ipsum eget magna pulvinar fringilla. Fusce rhoncus suscipit urna sit amet hendrerit. Phasellus at vulputate lorem.
', 'read');